services:
  redis:
    image: redis:7-alpine
    container_name: demo1-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: demo1-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: demo1_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  redis_data:
  rabbitmq_data:
  es_data:
